name = "spin-grannybonus-co-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-grannybonus.co.cz"
HMAC_KEY = "4ec4268a43a32d2b2070dc0ebf83ecade6f6b26774a16f17b5432c3fbd722745"
COOKIE_NAME = "3hd"
PLAY_PATH = "explore"
BUTTON_ID = "pa18f85e6033fd808240432fd1d473c70"
GATE_SALT = "415056bb0b33b1fa"
