name = "spin-grannybonus-co-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-grannybonus.co.cz"
HMAC_KEY = "4ec4268a43a32d2b2070dc0ebf83ecade6f6b26774a16f17b5432c3fbd722745"
COOKIE_NAME = "yvu"
PLAY_PATH = "visit"
BUTTON_ID = "pa18f85e6033fd808240432fd1d473c70"
GATE_SALT = "8dfa868408e282b8"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "k8aw"
CTA_SELECTOR = ".play-button"
